###
# List Feeds
GET localhost:8080/v1/feeds
Content-Type: application/json


###
# Create New Feed
POST localhost:8080/v1/feeds
Content-Type: application/json
Authorization: ApiKey bd5bf06cf44212cd15cfcbab2ce4f738223b7bdac7b34c6c1a8873c379735f6c

{
  "name": "Wagslane",
  "url": "https://blog.boot.dev/index.xml"
}

###
# Follow a Feed
POST localhost:8080/v1/feed_follows
Content-Type: application/json
Authorization: ApiKey bd5bf06cf44212cd15cfcbab2ce4f738223b7bdac7b34c6c1a8873c379735f6c

{
  "feed_id": "899825b5-eafc-4626-aece-e2c828d15291"
}

###
# Get Feed follows for a user
GET localhost:8080/v1/feed_follows
Content-Type: application/json
Authorization: ApiKey bd5bf06cf44212cd15cfcbab2ce4f738223b7bdac7b34c6c1a8873c379735f6c
