###
# List Feeds
GET localhost:8080/v1/feeds
Content-Type: application/json


###
# Create New Feed
POST localhost:8080/v1/feeds
Content-Type: application/json
Authorization: ApiKey 47438d7ecb9e13d636b85379df1f0273f87ee3c6709aa75ebc556ca1a1487c4c

{
  "name": "The Boot.dev Blog",
  "url": "https://blog.boot.dev/index.xml"
}

