GET http://localhost:8080/v1/users
Accept: application/json
Authorization: ApiKey 47438d7ecb9e13d636b85379df1f0273f87ee3c6709aa75ebc556ca1a1487c4c

###
# Create New User
POST localhost:8080/v1/users
Content-Type: application/json

{
  "name": "steven hansen"
}

